# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BuildingDepot
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        python-version: ['3.10']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Display Python version
        run: python --version
      - name: Install BuildingDepot
        run: |
          sudo bash -x ./script_for_github_actions.sh
      - name: Initialize tests
        run: |
          cd benchmarking-tools/functional-testing-tool
          npm install
      - name: Run tests
        run: |
          cd benchmarking-tools/functional-testing-tool
          npm test ./tests/all.js
